Fix compile error with --enable-location
```C
chilli.c: In function 'chilli_learn_location':
chilli.c:2964:9: error: 's_state' undeclared (first use in this
      function)
sizeof(s_state.pending_location));
```

s_state is declared in the appconn.

```C
sizeof(appconn->s_state.pending_location);
```

Signed-off-by: Baligh GUESMI gasmibal@gmail.com