configure: Remove AC_FUNC_MALLOC and AC_FUNC_REALLOC
Causing troubles while doing cross compilations:

  chilli.git/bstring/.libs/libbstring.a(bstrlib.o): In function `balloc':
  chilli.git/bstring/bstrlib.c:115: undefined reference to `rpl_realloc'
  chilli.git/bstring/bstrlib.c:121: undefined reference to `rpl_realloc'

Fixes #153

Signed-off-by: Petr Štetiar <ynezz@true.cz>